# docker-compose.yml
services:
  web:
    build: . # このディレクトリの Dockerfile を使ってイメージをビルドするよ
    # Flask開発サーバーを起動するコマンドだよ
    command: flask run --host=0.0.0.0 --port=5000
    # ホスト（君のPC）の現在のディレクトリをコンテナの /app にマウントするよ
    # これで、コードを変更したらコンテナ内で自動的に反映されるようになるんだ
    volumes:
      - .:/app
    # ホストの5000番ポートとコンテナの5000番ポートを繋ぐよ
    ports:
      - "5001:5000"
    # 環境変数ファイルを指定するよ（開発用）
    env_file:
      - ./.env